# Generated by Django 4.2.30 on 2026-05-01 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('time', models.CharField(default='02:00', help_text='HH:MM format', max_length=5)),
                ('day_of_week', models.CharField(blank=True, help_text='For weekly frequency', max_length=20)),
                ('day_of_month', models.IntegerField(default=1, help_text='For monthly frequency')),
                ('enabled', models.BooleanField(default=True)),
                ('encrypted', models.BooleanField(default=True)),
                ('compressed', models.BooleanField(default=True)),
                ('include_files', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('max_backups', models.IntegerField(default=30)),
                ('max_age_days', models.IntegerField(default=90)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, max_length=20)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Backup schedules',
                'db_table': 'backup_schedule',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('pre_update', 'Pre-Update'), ('pre_maintenance', 'Pre-Maintenance')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('verified', 'Verified'), ('restored', 'Restored'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('encrypted', models.BooleanField(default=False)),
                ('compressed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('database_path', models.CharField(blank=True, max_length=500)),
                ('database_size_bytes', models.BigIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_result', models.TextField(blank=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('restore_target_path', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_created', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_restored', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('event', models.CharField(choices=[('backup_started', 'Backup Started'), ('backup_completed', 'Backup Completed'), ('backup_failed', 'Backup Failed'), ('restore_started', 'Restore Started'), ('restore_completed', 'Restore Completed'), ('restore_failed', 'Restore Failed'), ('backup_deleted', 'Backup Deleted'), ('backup_verified', 'Backup Verified'), ('schedule_created', 'Schedule Created'), ('schedule_updated', 'Schedule Updated'), ('schedule_deleted', 'Schedule Deleted'), ('cleanup_started', 'Cleanup Started'), ('cleanup_completed', 'Cleanup Completed')], max_length=30)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('backup_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='backup.backuprecord')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='backup.backupschedule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['status', 'created_at'], name='backup_reco_status_dc1c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['backup_type', 'created_at'], name='backup_reco_backup__3c4b31_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['level', 'timestamp'], name='backup_log_level_b9e914_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['event', 'timestamp'], name='backup_log_event_158123_idx'),
        ),
    ]
