# Generated by Django 4.2.30 on 2026-05-02 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('validated', 'Validated'), ('failed', 'Failed'), ('restored', 'Restored'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('restore_started_at', models.DateTimeField(blank=True, null=True)),
                ('restore_completed_at', models.DateTimeField(blank=True, null=True)),
                ('can_rollback', models.BooleanField(default=True)),
                ('rollback_reason', models.TextField(blank=True)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('backup_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_points', to='backup.backuprecord')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores_performed', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_restore_point',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validation_type', models.CharField(choices=[('schema', 'Schema Validation'), ('data_integrity', 'Data Integrity'), ('foreign_key', 'Foreign Key Check'), ('business_rule', 'Business Rule'), ('transaction', 'Transaction Check')], max_length=30)),
                ('is_valid', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('restore_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='backup.restorepoint')),
            ],
            options={
                'db_table': 'backup_restore_validation',
            },
        ),
        migrations.AddIndex(
            model_name='restorepoint',
            index=models.Index(fields=['status', 'created_at'], name='backup_rest_status_f1f56e_idx'),
        ),
        migrations.AddIndex(
            model_name='restorepoint',
            index=models.Index(fields=['backup_record', 'status'], name='backup_rest_backup__e970cc_idx'),
        ),
    ]
