# Generated by Django 4.2.30 on 2026-04-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='journal_entry_id',
            field=models.UUIDField(blank=True, help_text='Linked accounting journal entry', null=True, verbose_name='Journal Entry ID'),
        ),
    ]
