# Generated by Django 4.2.30 on 2026-05-05 17:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseinvoice_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='payment_terms',
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact Role'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='delivery_terms',
            field=models.CharField(blank=True, help_text='e.g., FOB, CIF, Ex-Works', max_length=200, verbose_name='Delivery Terms'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='iban',
            field=models.CharField(blank=True, max_length=50, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='lead_time_days',
            field=models.IntegerField(default=0, verbose_name='Lead Time (Days)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='minimum_order_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Minimum Order Value'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.IntegerField(default=0, verbose_name='Payment Terms (Days)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='quality_rating',
            field=models.IntegerField(default=0, help_text='Supplier quality rating from 0 to 5', verbose_name='Quality Rating (0-5)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20, verbose_name='Risk Level'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='subtype',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], default='COMPANY', max_length=20, verbose_name='Party Subtype'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supply_categories',
            field=models.CharField(blank=True, help_text='Categories of products supplied (e.g., Medicines, Medical Devices, Cosmetics)', max_length=500, verbose_name='Supply Categories'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='swift_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='SWIFT Code'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['subtype'], name='purchases_s_subtype_3be355_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['status'], name='purchases_s_status_c38f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['quality_rating'], name='purchases_s_quality_49f6c1_idx'),
        ),
    ]
