# Generated by Django 4.2.30 on 2026-05-20 08:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchaseinvoice_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Allocated Amount')),
                ('allocated_at', models.DateTimeField(auto_now_add=True, verbose_name='Allocated At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='purchases.purchaseinvoice', verbose_name='Purchase Invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='purchases.supplierpayment', verbose_name='Supplier Payment')),
            ],
            options={
                'verbose_name': 'Supplier Payment Allocation',
                'verbose_name_plural': 'Supplier Payment Allocations',
                'ordering': ['-allocated_at'],
                'indexes': [models.Index(fields=['payment', 'invoice'], name='purchases_s_payment_226564_idx')],
            },
        ),
    ]
