# Generated by Django 4.2.30 on 2026-06-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_purchaseinvoice_tax_enabled_purchaseinvoice_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(help_text='Supplier invoice number per company', max_length=100, verbose_name='Invoice Number'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_number'), name='uniq_purchase_invoice_number_per_company'),
        ),
    ]
