# Generated by Django 6.0.6 on 2026-06-18 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_financialtransaction_company_and_more'),
        ('purchases', '0009_forensic_audit_fixes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseinvoice',
            name='uniq_purchase_invoice_number_per_company',
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Payment account used for this transaction. If not specified, system will select default.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='payments.paymentaccount', verbose_name='Payment Account'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(help_text='Supplier invoice number', max_length=100, unique=True, verbose_name='Invoice Number'),
        ),
    ]
