# Generated by Django 4.2.30 on 2026-05-03 11:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Category Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Default Tax Rate (%)')),
                ('is_exempt', models.BooleanField(default=False, help_text='Category is exempt from tax', verbose_name='Is Exempt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Tax Category',
                'verbose_name_plural': 'Tax Categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TaxJurisdiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Jurisdiction Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Tax Jurisdiction',
                'verbose_name_plural': 'Tax Jurisdictions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Rate Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Rate Code')),
                ('rate_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rate Percentage')),
                ('tax_type', models.CharField(choices=[('STANDARD', 'Standard'), ('REDUCED', 'Reduced'), ('EXEMPT', 'Exempt'), ('ZERO', 'Zero Rated')], default='STANDARD', max_length=20, verbose_name='Tax Type')),
                ('effective_from', models.DateField(verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FILED', 'Filed'), ('PAID', 'Paid'), ('ADJUSTED', 'Adjusted')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Gross Sales')),
                ('exempt_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Exempt Sales')),
                ('taxable_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Taxable Sales')),
                ('output_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Output Tax')),
                ('input_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Input Tax')),
                ('net_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Net Tax Payable')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='Filing Date')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Tax Return',
                'verbose_name_plural': 'Tax Returns',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('ADJUSTMENT', 'Adjustment')], max_length=20, verbose_name='Transaction Type')),
                ('reference_id', models.UUIDField(verbose_name='Reference ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Base Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tax Amount')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='Is Reversed')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tax.taxrate', verbose_name='Tax Rate')),
                ('tax_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tax.taxreturn', verbose_name='Tax Return')),
            ],
            options={
                'verbose_name': 'Tax Transaction',
                'verbose_name_plural': 'Tax Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='taxreturn',
            index=models.Index(fields=['period_start', 'period_end'], name='tax_taxretu_period__789517_idx'),
        ),
        migrations.AddIndex(
            model_name='taxreturn',
            index=models.Index(fields=['status'], name='tax_taxretu_status_6d1882_idx'),
        ),
        migrations.AddField(
            model_name='taxjurisdiction',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurisdictions', to='tax.taxrate', verbose_name='Default Tax Rate'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['transaction_type', 'transaction_date'], name='tax_taxtran_transac_f3b7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['tax_return'], name='tax_taxtran_tax_ret_a07efe_idx'),
        ),
    ]
