# Generated by Django 4.2.30 on 2026-05-06 12:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_usercompanymapping'),
        ('security', '0003_fix_notification_object_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Chain Name')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(choices=[('SALES_INVOICE', 'Sales Invoice'), ('PURCHASE_INVOICE', 'Purchase Invoice'), ('RETURN_ORDER', 'Return Order'), ('JOURNAL_ENTRY', 'Journal Entry'), ('PAYMENT', 'Payment')], max_length=30, verbose_name='Entity Type')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Approval Chain',
                'verbose_name_plural': 'Approval Chains',
                'db_table': 'approval_chain',
            },
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('level_number', models.PositiveIntegerField()),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('999999999'), max_digits=15)),
                ('approver_type', models.CharField(choices=[('USER', 'Specific User'), ('ROLE', 'Role-based'), ('MANAGER', 'Manager'), ('DEPARTMENT_HEAD', 'Department Head')], default='ROLE', max_length=20)),
                ('approver_id', models.UUIDField(blank=True, null=True)),
                ('timeout_hours', models.PositiveIntegerField(default=48)),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.role')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='workflows.approvalchain')),
            ],
            options={
                'db_table': 'approval_level',
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(choices=[('SALES_INVOICE', 'Sales Invoice'), ('PURCHASE_INVOICE', 'Purchase Invoice'), ('RETURN_ORDER', 'Return Order'), ('JOURNAL_ENTRY', 'Journal Entry')], max_length=30, verbose_name='Applies To')),
                ('conditions', models.JSONField(default=dict, verbose_name='Conditions')),
                ('target_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], max_length=30)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('required_roles', models.ManyToManyField(blank=True, to='security.role', verbose_name='Required Roles')),
            ],
            options={
                'db_table': 'workflow_rule',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_submit', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_reject', models.BooleanField(default=False)),
                ('can_post', models.BooleanField(default=False)),
                ('can_cancel', models.BooleanField(default=False)),
                ('can_override', models.BooleanField(default=False)),
                ('entity_type', models.CharField(blank=True, max_length=30)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('999999999'), max_digits=15)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_permissions', to='security.role')),
            ],
            options={
                'db_table': 'workflow_permission',
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(max_length=50, verbose_name='Entity Type')),
                ('object_id', models.UUIDField(verbose_name='Entity ID')),
                ('object_reference', models.CharField(blank=True, max_length=200, verbose_name='Object Reference')),
                ('current_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=30)),
                ('previous_state', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(default='NORMAL', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('current_approval_level', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('currency', models.CharField(default='AFN', max_length=3)),
                ('approval_chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.approvalchain')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('pending_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_instance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('from_state', models.CharField(blank=True, max_length=30)),
                ('to_state', models.CharField(max_length=30)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workflows.workflowinstance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('currency', models.CharField(default='AFN', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_comment', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.approvalchain')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.approvallevel')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='workflows.workflowinstance')),
            ],
            options={
                'db_table': 'approval_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='workflow_in_content_9e4801_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['company', 'current_state'], name='workflow_in_company_c8f985_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['current_state', 'is_active'], name='workflow_in_current_678320_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['pending_approver', 'current_state'], name='workflow_in_pending_c3ff22_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowauditlog',
            index=models.Index(fields=['instance', 'created_at'], name='workflow_au_instanc_e97ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowauditlog',
            index=models.Index(fields=['user', 'created_at'], name='workflow_au_user_id_89b381_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvallevel',
            unique_together={('chain', 'level_number')},
        ),
    ]
