# Generated by Django 4.2.30 on 2026-05-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflowpermission_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowinstance',
            unique_together={('content_type', 'object_id', 'is_active')},
        ),
    ]
