# Generated by Django 4.2.30 on 2026-06-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_workflowinstance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowauditlog',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='workflows.workflowinstance'),
        ),
    ]
