# Generated by Django 4.2.30 on 2026-05-05 17:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_fiscal_period'),
        ('sales', '0004_remove_customer_payment_terms_and_more'),
        ('hr', '0002_overtime_leave_attendance'),
        ('purchases', '0004_remove_purchaseinvoice_entity_and_more'),
        ('inventory', '0008_remove_stockmovement_entity_alter_batch_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_number', models.CharField(help_text='Auto-generated return identifier', max_length=50, unique=True, verbose_name='Return Number')),
                ('return_type', models.CharField(choices=[('SALE_RETURN', 'Sale Return'), ('PURCHASE_RETURN', 'Purchase Return')], max_length=20, verbose_name='Return Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Return Amount')),
                ('reason', models.TextField(verbose_name='Return Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('credit_note_number', models.CharField(blank=True, max_length=50, verbose_name='Credit Note Number')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to='hr.employee', verbose_name='Approved By')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.salesinvoice', verbose_name='Sales Invoice')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='accounting.journalentry', verbose_name='Journal Entry')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.customer', verbose_name='Customer')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchases.purchaseinvoice', verbose_name='Purchase Invoice')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchases.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Return Order',
                'verbose_name_plural': 'Return Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Return Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Price')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='inventory.batch', verbose_name='Batch')),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='sales.salesitem', verbose_name='Invoice Item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='inventory.product', verbose_name='Product')),
                ('purchase_invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='purchases.purchaseitem', verbose_name='Purchase Invoice Item')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnorder', verbose_name='Return Order')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
            },
        ),
        migrations.AddIndex(
            model_name='returnorder',
            index=models.Index(fields=['return_number'], name='returns_ret_return__35ada9_idx'),
        ),
        migrations.AddIndex(
            model_name='returnorder',
            index=models.Index(fields=['return_type'], name='returns_ret_return__815ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='returnorder',
            index=models.Index(fields=['status'], name='returns_ret_status_00e90e_idx'),
        ),
        migrations.AddIndex(
            model_name='returnorder',
            index=models.Index(fields=['invoice'], name='returns_ret_invoice_1dd500_idx'),
        ),
        migrations.AddIndex(
            model_name='returnorder',
            index=models.Index(fields=['party'], name='returns_ret_party_i_f3bcc2_idx'),
        ),
    ]
