# Generated by Django 4.2.30 on 2026-05-05 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_customer_payment_terms_and_more'),
        ('purchases', '0004_remove_purchaseinvoice_entity_and_more'),
        ('hr', '0002_overtime_leave_attendance'),
        ('accounting', '0005_fiscal_period'),
        ('core', '0002_usercompanymapping'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('RETURN', 'Return'), ('PAYMENT', 'Payment'), ('ADJUSTMENT', 'Adjustment')], max_length=20, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('MISMATCHED', 'Mismatch'), ('FIXED', 'Fixed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('fixed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fixed At')),
                ('fix_notes', models.TextField(blank=True, verbose_name='Fix Notes')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('accounting_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_entries', to='accounting.journalentry', verbose_name='Journal Entry')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_entries', to='core.company', verbose_name='Company')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_reconciliations', to='hr.employee', verbose_name='Fixed By')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_entries', to='sales.salesinvoice', verbose_name='Sales Invoice')),
                ('linked_reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_entries', to='returns.reconciliationentry', verbose_name='Linked Reconciliation')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_entries', to='sales.customer', verbose_name='Customer')),
                ('return_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_entries', to='returns.returnorder', verbose_name='Return Order')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_entries', to='purchases.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Reconciliation Entry',
                'verbose_name_plural': 'Reconciliation Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='returns_rec_status_3759ad_idx'), models.Index(fields=['transaction_type'], name='returns_rec_transac_3e4a55_idx'), models.Index(fields=['invoice'], name='returns_rec_invoice_cee263_idx'), models.Index(fields=['return_order'], name='returns_rec_return__43ffa0_idx'), models.Index(fields=['accounting_entry'], name='returns_rec_account_850949_idx'), models.Index(fields=['company'], name='returns_rec_company_eea424_idx')],
            },
        ),
    ]
