# Generated by Django 4.2.30 on 2026-05-07 05:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_reconciliationentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'Good (Back to Stock)'), ('DAMAGED', 'Damaged (Quarantine)'), ('EXPIRED', 'Expired (Quarantine)')], default='GOOD', max_length=20, verbose_name='Item Condition'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tax Amount'),
        ),
    ]
