# Generated by Django 4.2.30 on 2026-05-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_add_return_entry_types'),
        ('hr', '0002_overtime_leave_attendance'),
        ('returns', '0003_returnitem_condition_returnitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='reversal_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_returns', to='accounting.journalentry', verbose_name='Reversal Journal Entry'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='void_reason',
            field=models.TextField(blank=True, verbose_name='Void Reason'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Voided At'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_returns', to='hr.employee', verbose_name='Voided By'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('VOIDED', 'Voided')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
