# Generated by Django 4.2.30 on 2026-04-29 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., AFN, USD)', max_length=3, unique=True, verbose_name='Currency Code')),
                ('name', models.CharField(max_length=50, verbose_name='Currency Name')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Currency')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate applied if currency differs from base currency', max_digits=15, null=True, verbose_name='Exchange Rate')),
                ('amount_in_base', models.DecimalField(blank=True, decimal_places=2, help_text='Converted amount in the system base currency', max_digits=12, null=True, verbose_name='Amount in Base Currency')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('HAWALA', 'Hawala'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], max_length=20, verbose_name='Payment Method')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale Payment'), ('PURCHASE', 'Purchase Payment'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], max_length=20, verbose_name='Transaction Type')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('invoice_model', models.CharField(max_length=100, verbose_name='Invoice Model')),
                ('invoice_id', models.UUIDField(verbose_name='Invoice ID')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='accounting.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('rate', models.DecimalField(decimal_places=6, help_text='1 unit of from_currency equals this many units of to_currency', max_digits=15, verbose_name='Exchange Rate')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('source', models.CharField(blank=True, help_text='Source of the exchange rate (e.g., Central Bank, Manual)', max_length=100, verbose_name='Source')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_exchange_rates', to='accounting.currency', verbose_name='From Currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_exchange_rates', to='accounting.currency', verbose_name='To Currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['code'], name='accounting__code_00a2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_610118_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_date'], name='accounting__payment_7d632c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_method'], name='accounting__payment_ad2cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['currency'], name='accounting__currenc_6e7b74_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_type'], name='accounting__transac_d9b8be_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['invoice_model', 'invoice_id'], name='accounting__invoice_ea38e8_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency', 'effective_date'], name='accounting__from_cu_da9c92_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['effective_date'], name='accounting__effecti_66ebe3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_currency', 'to_currency', 'effective_date')},
        ),
    ]
