# Generated by Django 4.2.30 on 2026-04-29 15:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Account Name')),
                ('code', models.CharField(help_text='Unique account code (e.g., 1000, 1100, 1110)', max_length=20, unique=True, verbose_name='Account Code')),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=20, verbose_name='Account Type')),
                ('account_category', models.CharField(blank=True, choices=[('CURRENT_ASSET', 'Current Asset'), ('FIXED_ASSET', 'Fixed Asset'), ('INTANGIBLE_ASSET', 'Intangible Asset'), ('CURRENT_LIABILITY', 'Current Liability'), ('LONG_TERM_LIABILITY', 'Long Term Liability'), ('OWNER_EQUITY', 'Owner Equity'), ('OPERATING_REVENUE', 'Operating Revenue'), ('NON_OPERATING_REVENUE', 'Non Operating Revenue'), ('COST_OF_GOODS_SOLD', 'Cost of Goods Sold'), ('OPERATING_EXPENSE', 'Operating Expense'), ('NON_OPERATING_EXPENSE', 'Non Operating Expense')], max_length=30, verbose_name='Account Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_system', models.BooleanField(default=False, help_text='System accounts cannot be deleted', verbose_name='Is System Account')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated from journal entries', max_digits=15, verbose_name='Current Balance')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('entry_number', models.CharField(max_length=50, unique=True, verbose_name='Entry Number')),
                ('entry_date', models.DateField(verbose_name='Entry Date')),
                ('entry_type', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('OPENING', 'Opening Balance'), ('CLOSING', 'Closing Balance')], max_length=20, verbose_name='Entry Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('is_posted', models.BooleanField(default=False, help_text='Posted entries cannot be modified', verbose_name='Is Posted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Credit')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Line Description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account', verbose_name='Account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='Journal Entry')),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_number'], name='accounting__entry_n_734b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_date'], name='accounting__entry_d_79c286_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_type'], name='accounting__entry_t_5e6cde_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['is_posted'], name='accounting__is_post_95b69a_idx'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account', verbose_name='Parent Account'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account'], name='accounting__account_6fdc67_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['entry'], name='accounting__entry_i_27304d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='accounting__code_c93a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type'], name='accounting__account_889d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_category'], name='accounting__account_e97db3_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_28dd04_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['parent'], name='accounting__parent__da6035_idx'),
        ),
    ]
