# Generated by Django 4.2.30 on 2026-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_journalentry_journalentryline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_category',
            field=models.CharField(blank=True, choices=[('CURRENT_ASSET', 'Current Asset'), ('FIXED_ASSET', 'Fixed Asset'), ('INTANGIBLE_ASSET', 'Intangible Asset'), ('CURRENT_LIABILITY', 'Current Liability'), ('LONG_TERM_LIABILITY', 'Long Term Liability'), ('OWNER_EQUITY', 'Owner Equity'), ('OPERATING_REVENUE', 'Operating Revenue'), ('NON_OPERATING_REVENUE', 'Non Operating Revenue'), ('COST_OF_GOODS_SOLD', 'Cost of Goods Sold'), ('OPERATING_EXPENSE', 'Operating Expense'), ('NON_OPERATING_EXPENSE', 'Non Operating Expense')], max_length=30, null=True, verbose_name='Account Category'),
        ),
    ]
