# Generated by Django 4.2.30 on 2026-05-04 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0004_journalentry_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='entity',
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Period Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Period Code')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked - No Changes Allowed')], default='OPEN', max_length=20, verbose_name='Status')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Is Locked')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Locked At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_periods', to=settings.AUTH_USER_MODEL, verbose_name='Locked By')),
            ],
            options={
                'verbose_name': 'Fiscal Period',
                'verbose_name_plural': 'Fiscal Periods',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status'], name='accounting__status_ee6e5a_idx'), models.Index(fields=['is_locked'], name='accounting__is_lock_5f0703_idx'), models.Index(fields=['start_date', 'end_date'], name='accounting__start_d_9f449b_idx')],
            },
        ),
    ]
