# Generated by Django 4.2.30 on 2026-05-10 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0006_account_company_journalentry_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('MODIFIED', 'Modified'), ('POSTED', 'Posted'), ('UNPOSTED', 'Unposted'), ('REVERSED', 'Reversed'), ('CANCELLED', 'Cancelled'), ('VIEWED', 'Viewed')], max_length=20, verbose_name='Event Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'Journal Event Log',
                'verbose_name_plural': 'Journal Event Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='change_reason',
            field=models.TextField(blank=True, help_text='Reason for creation or modification', verbose_name='Change Reason'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='original_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_entries', to='accounting.journalentry', verbose_name='Original Entry (for reversals)'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_posted', to=settings.AUTH_USER_MODEL, verbose_name='Posted By'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_by_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses_entry', to='accounting.journalentry', verbose_name='Reversed By'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_document',
            field=models.CharField(blank=True, help_text='Reference to source document ID (e.g., invoice UUID)', max_length=100, verbose_name='Source Document'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_module',
            field=models.CharField(blank=True, help_text='Module that created this entry (e.g., sales, purchases, inventory, payroll)', max_length=50, verbose_name='Source Module'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('OPENING', 'Opening Balance'), ('CLOSING', 'Closing Balance'), ('INVENTORY_IN', 'Inventory Receipt'), ('INVENTORY_OUT', 'Inventory Issue'), ('INVENTORY_ADJ', 'Inventory Adjustment'), ('PAYROLL', 'Payroll'), ('REVERSAL', 'Reversal')], max_length=20, verbose_name='Entry Type'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_module'], name='accounting__source__37d1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_document'], name='accounting__source__66cf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['created_by'], name='accounting__created_54482c_idx'),
        ),
        migrations.AddField(
            model_name='journaleventlog',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='accounting.journalentry', verbose_name='Journal Entry'),
        ),
        migrations.AddField(
            model_name='journaleventlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_events', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='journaleventlog',
            index=models.Index(fields=['entry'], name='accounting__entry_i_4eb9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='journaleventlog',
            index=models.Index(fields=['event_type'], name='accounting__event_t_9cc35e_idx'),
        ),
        migrations.AddIndex(
            model_name='journaleventlog',
            index=models.Index(fields=['user'], name='accounting__user_id_a7a7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='journaleventlog',
            index=models.Index(fields=['timestamp'], name='accounting__timesta_1cc229_idx'),
        ),
    ]
