# Generated by Django 4.2.30 on 2026-05-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_add_journal_entry_audit_fields_and_event_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('OPENING', 'Opening Balance'), ('CLOSING', 'Closing Balance'), ('INVENTORY_IN', 'Inventory Receipt'), ('INVENTORY_OUT', 'Inventory Issue'), ('INVENTORY_ADJ', 'Inventory Adjustment'), ('PAYROLL', 'Payroll'), ('REVERSAL', 'Reversal'), ('SALE_RETURN', 'Sale Return'), ('PURCHASE_RETURN', 'Purchase Return')], max_length=20, verbose_name='Entry Type'),
        ),
    ]
