# Generated by Django 4.2.30 on 2026-05-21 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_add_decision_record'),
        ('accounting', '0008_add_return_entry_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalPeriodCloseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CLOSE', 'Close Period'), ('SOFT_CLOSE', 'Soft Close Period'), ('REOPEN', 'Reopen Period'), ('LOCK', 'Lock Period'), ('CARRY_FORWARD', 'Carry Forward Balances')], max_length=20, verbose_name='Action')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('previous_status', models.CharField(max_length=20, verbose_name='Previous Status')),
                ('new_status', models.CharField(max_length=20, verbose_name='New Status')),
                ('validation_summary', models.JSONField(blank=True, default=dict, verbose_name='Validation Summary')),
                ('affected_entries_count', models.IntegerField(default=0, verbose_name='Affected Journal Entries Count')),
            ],
            options={
                'verbose_name': 'Fiscal Period Close Log',
                'verbose_name_plural': 'Fiscal Period Close Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='closing_balance_carried_forward',
            field=models.BooleanField(default=False, verbose_name='Closing Balance Carried Forward'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='closing_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closing Completed At'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='closing_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_period_closures', to=settings.AUTH_USER_MODEL, verbose_name='Closing Completed By'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Period Code'),
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SOFT_CLOSED', 'Soft Closed'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked - No Changes Allowed')], default='OPEN', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('code', 'company')},
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['company', 'status'], name='accounting__company_ffe203_idx'),
        ),
        migrations.AddField(
            model_name='fiscalperiodcloselog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_close_actions', to=settings.AUTH_USER_MODEL, verbose_name='Performed By'),
        ),
        migrations.AddField(
            model_name='fiscalperiodcloselog',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_logs', to='accounting.fiscalperiod', verbose_name='Fiscal Period'),
        ),
        migrations.AddIndex(
            model_name='fiscalperiodcloselog',
            index=models.Index(fields=['period', 'action'], name='accounting__period__23ee54_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalperiodcloselog',
            index=models.Index(fields=['performed_by'], name='accounting__perform_389f88_idx'),
        ),
    ]
