# Generated by Django 4.2.30 on 2026-06-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_journalentry_list_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='journalentry',
            name='je_company_entry_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='je_created_at_desc_idx',
        ),
        migrations.AlterField(
            model_name='fiscalperiodcloselog',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_logs', to='accounting.fiscalperiod', verbose_name='Fiscal Period'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_number',
            field=models.CharField(max_length=50, verbose_name='Entry Number'),
        ),
        migrations.AlterField(
            model_name='journaleventlog',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_logs', to='accounting.journalentry', verbose_name='Journal Entry'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('company', 'entry_number'), name='uniq_journal_entry_number_per_company'),
        ),
    ]
