# Generated by Django 6.0.6 on 2026-06-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_forensic_audit_fixes'),
        ('core', '0007_add_company_business_config'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='uniq_journal_entry_number_per_company',
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(help_text='Unique account code (e.g., 1000, 1100, 1110)', max_length=20, verbose_name='Account Code'),
        ),
        migrations.AlterField(
            model_name='fiscalperiodcloselog',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_logs', to='accounting.fiscalperiod', verbose_name='Fiscal Period'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Entry Number'),
        ),
        migrations.AlterField(
            model_name='journaleventlog',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='accounting.journalentry', verbose_name='Journal Entry'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('code', 'company')},
        ),
    ]
