# Generated by Django 4.2.30 on 2026-04-30 02:32

from django.db import migrations, models
import django.utils.timezone
import licensing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(help_text='Unique license key', max_length=255, unique=True)),
                ('device_fingerprint', models.JSONField(help_text='Device hardware fingerprint', validators=[licensing.models.validate_device_fingerprint])),
                ('device_id', models.CharField(help_text='Unique device identifier based on hardware fingerprint', max_length=64, unique=True)),
                ('license_type', models.CharField(default='pharmacy_erp', help_text='Type of license', max_length=50)),
                ('issued_date', models.DateField(default=django.utils.timezone.now, help_text='Date when license was issued')),
                ('expires_date', models.DateField(blank=True, help_text='Date when license expires (null for perpetual)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the license is currently active')),
                ('issued_to', models.CharField(blank=True, help_text='Name or organization the license was issued to', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the license')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device License',
                'verbose_name_plural': 'Device Licenses',
                'db_table': 'licensing_devicelicense',
                'ordering': ['-created_at'],
            },
        ),
    ]
