# Generated by Django 4.2.30 on 2026-04-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelicense',
            name='signed_license',
            field=models.TextField(blank=True, help_text='RSA-signed license data for verification'),
        ),
    ]
