# Generated by Django 4.2.30 on 2026-05-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_devicelicense_signed_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier (SHA256 of hardware fingerprint)', max_length=64, unique=True)),
                ('device_fingerprint', models.JSONField(default=dict, help_text='Snapshot of device hardware at trial start')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the trial period began')),
                ('expires_at', models.DateTimeField(help_text='When the trial period ends')),
                ('extended', models.BooleanField(default=False, help_text='Whether trial has been extended')),
                ('access_count', models.IntegerField(default=1, help_text='Number of times license has been checked during trial')),
            ],
            options={
                'verbose_name': 'Trial Session',
                'verbose_name_plural': 'Trial Sessions',
                'db_table': 'licensing_trialsession',
                'ordering': ['-started_at'],
            },
        ),
    ]
