# Generated by Django 4.2.30 on 2026-05-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_add_trialsession_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelicense',
            name='fingerprint_hash',
            field=models.CharField(blank=True, help_text='SHA-256 fingerprint hash at time of license creation', max_length=64),
        ),
        migrations.AddField(
            model_name='devicelicense',
            name='last_server_sync',
            field=models.DateTimeField(blank=True, help_text='Last successful sync with license server', null=True),
        ),
        migrations.AddField(
            model_name='devicelicense',
            name='last_validated_at',
            field=models.DateTimeField(blank=True, help_text='Last successful license validation timestamp', null=True),
        ),
        migrations.AddField(
            model_name='devicelicense',
            name='tamper_count',
            field=models.IntegerField(default=0, help_text='Number of tamper events detected'),
        ),
        migrations.CreateModel(
            name='LicenseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('clock_rollback', 'System Clock Rollback'), ('fingerprint_mismatch', 'Device Fingerprint Mismatch'), ('file_modified', 'License File Modified'), ('signature_failed', 'Signature Verification Failed'), ('too_many_failures', 'Excessive Validation Failures')], help_text='Type of tamper/security event', max_length=32)),
                ('device_id', models.CharField(help_text='Device ID at time of event', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Event details including state context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'License Audit Log Entry',
                'verbose_name_plural': 'License Audit Logs',
                'db_table': 'licensing_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_id', 'event_type'], name='licensing_a_device__4c410e_idx'), models.Index(fields=['created_at'], name='licensing_a_created_bcf65a_idx')],
            },
        ),
    ]
