# Generated by Django 4.2.30 on 2026-05-24 09:45

from django.db import migrations, models
import django.utils.timezone
import licensing.models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_add_antitamper_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicenseAuditLog',
        ),
        migrations.RemoveField(
            model_name='devicelicense',
            name='fingerprint_hash',
        ),
        migrations.RemoveField(
            model_name='devicelicense',
            name='last_server_sync',
        ),
        migrations.RemoveField(
            model_name='devicelicense',
            name='last_validated_at',
        ),
        migrations.RemoveField(
            model_name='devicelicense',
            name='tamper_count',
        ),
        migrations.AlterField(
            model_name='devicelicense',
            name='device_fingerprint',
            field=models.JSONField(validators=[licensing.models.validate_device_fingerprint]),
        ),
        migrations.AlterField(
            model_name='devicelicense',
            name='device_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='devicelicense',
            name='expires_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicelicense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='devicelicense',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='devicelicense',
            name='issued_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='devicelicense',
            name='license_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='devicelicense',
            name='license_type',
            field=models.CharField(default='pharmacy_erp', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicelicense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='devicelicense',
            name='signed_license',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trialsession',
            name='access_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trialsession',
            name='device_fingerprint',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='trialsession',
            name='device_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='trialsession',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trialsession',
            name='extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trialsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
