# Generated by Django 4.2.30 on 2026-05-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_simplify_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelicense',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='devicelicense',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='devicelicense',
            name='max_branches',
            field=models.IntegerField(default=1),
        ),
    ]
