# Generated by Django 4.2.30 on 2026-05-03 11:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_fix_account_category_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Budget Name')),
                ('fiscal_year', models.PositiveIntegerField(help_text='Budget fiscal year (e.g., 2025)', verbose_name='Fiscal Year')),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='ANNUAL', max_length=20, verbose_name='Period Type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('total_budgeted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Budgeted')),
                ('total_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Actual')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_by', models.CharField(blank=True, max_length=255, verbose_name='Approved By')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='Approved Date')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-fiscal_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('period', models.CharField(help_text='Period code (e.g., 2025-01, 2025-Q1, or ANNUAL)', max_length=20, verbose_name='Period')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Budgeted Amount')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Actual Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounting.account', verbose_name='Account')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budgeting.budget', verbose_name='Budget')),
            ],
            options={
                'verbose_name': 'Budget Line',
                'verbose_name_plural': 'Budget Lines',
                'ordering': ['period', 'account__code'],
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['fiscal_year'], name='budgeting_b_fiscal__21d77d_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['status'], name='budgeting_b_status_6c7665_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('name', 'fiscal_year')},
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['budget', 'period'], name='budgeting_b_budget__34eca7_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['account', 'period'], name='budgeting_b_account_7af8d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetline',
            unique_together={('budget', 'account', 'period')},
        ),
    ]
