# Generated by Django 4.2.30 on 2026-05-24 04:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_alter_budget_created_at_alter_budget_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetline',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Derived from posted journal entries. Read-only.', max_digits=15, verbose_name='Actual Amount'),
        ),
    ]
