# Generated by Django 4.2.30 on 2026-05-03 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidgetConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('widget_type', models.CharField(choices=[('KPI_CARD', 'KPI Card'), ('REVENUE_TREND', 'Revenue Trend'), ('PROFIT_TREND', 'Profit Trend'), ('EXPENSE_BREAKDOWN', 'Expense Breakdown'), ('CASH_FLOW_SUMMARY', 'Cash Flow Summary'), ('STOCK_VALUE_WAREHOUSE', 'Stock Value by Warehouse'), ('LOW_STOCK_ALERTS', 'Low Stock Alerts'), ('EXPIRY_RISK', 'Expiry Risk'), ('FAST_MOVING_PRODUCTS', 'Fast Moving Products'), ('TRIAL_BALANCE_SNAPSHOT', 'Trial Balance Snapshot'), ('LEDGER_ACTIVITY', 'Ledger Activity'), ('JE_VOLUME', 'Journal Entry Volume'), ('COST_CENTER_PERF', 'Cost Center Performance'), ('BUDGET_VARIANCE', 'Budget Variance'), ('VARIANCE_HEATMAP', 'Variance Heatmap'), ('AR_AGING', 'AR Aging'), ('AP_AGING', 'AP Aging'), ('TAX_LIABILITY', 'Tax Liability'), ('PAYROLL_SUMMARY', 'Payroll Summary'), ('ASSET_SUMMARY', 'Asset Summary')], max_length=30, verbose_name='Widget Type')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('size', models.CharField(default='MEDIUM', max_length=20, verbose_name='Size')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is Visible')),
                ('filter_config', models.JSONField(blank=True, default=dict, verbose_name='Filter Config')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_configs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Dashboard Widget Config',
                'verbose_name_plural': 'Dashboard Widget Configs',
                'ordering': ['user', 'position'],
            },
        ),
        migrations.CreateModel(
            name='DashboardAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10, verbose_name='Severity')),
                ('category', models.CharField(choices=[('FINANCIAL', 'Financial'), ('INVENTORY', 'Inventory'), ('ACCOUNTING', 'Accounting'), ('BUDGET', 'Budget'), ('TAX', 'Tax'), ('PAYROLL', 'Payroll'), ('SYSTEM', 'System')], max_length=20, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Is Acknowledged')),
                ('source_model', models.CharField(blank=True, max_length=100, verbose_name='Source Model')),
                ('source_id', models.CharField(blank=True, max_length=50, verbose_name='Source ID')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Acknowledged By')),
            ],
            options={
                'verbose_name': 'Dashboard Alert',
                'verbose_name_plural': 'Dashboard Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', 'is_active'], name='dashboard_d_severit_4639ee_idx'), models.Index(fields=['category', 'is_active'], name='dashboard_d_categor_686ddc_idx')],
            },
        ),
    ]
