# Generated by Django 4.2.30 on 2026-04-29 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_parent_alter_category_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('batch_number', models.CharField(max_length=100, unique=True, verbose_name='Batch Number')),
                ('manufacturing_date', models.DateField(help_text='Date when the batch was manufactured', verbose_name='Manufacturing Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Purchase price per unit', max_digits=10, verbose_name='Purchase Price')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Sale price per unit', max_digits=10, verbose_name='Sale Price')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Total quantity in this batch', max_digits=10, verbose_name='Quantity')),
                ('remaining_quantity', models.DecimalField(decimal_places=2, help_text='Quantity remaining in stock', max_digits=10, verbose_name='Remaining Quantity')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['expiry_date', 'manufacturing_date'],
                'indexes': [models.Index(fields=['expiry_date'], name='inventory_b_expiry__96c551_idx'), models.Index(fields=['product', 'expiry_date'], name='inventory_b_product_daa597_idx')],
            },
        ),
    ]
