# Generated by Django 4.2.30 on 2026-04-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_warehouse_stockmovement'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_number'], name='inventory_b_batch_n_6c5580_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['location'], name='inventory_b_locatio_5ba194_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['generic_name'], name='inventory_p_generic_28cf83_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand_name'], name='inventory_p_brand_n_ff9ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['batch', 'created_at'], name='inventory_s_batch_i_8a6d71_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_5aaa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['name'], name='inventory_w_name_703b74_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='inventory_w_code_2cdc02_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='inventory_w_is_acti_3ddeac_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_default'], name='inventory_w_is_defa_4b7615_idx'),
        ),
    ]
