# Generated by Django 4.2.30 on 2026-05-02 06:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_batch_inventory_b_batch_n_6c5580_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('transfer_number', models.CharField(max_length=50, unique=True, verbose_name='Transfer Number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('transfer_date', models.DateField(verbose_name='Transfer Date')),
                ('expected_arrival_date', models.DateField(blank=True, null=True, verbose_name='Expected Arrival Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.warehouse', verbose_name='Destination Warehouse')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='inventory.warehouse', verbose_name='Source Warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Transfer',
                'verbose_name_plural': 'Warehouse Transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('quantity_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Quantity Received')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.batch', verbose_name='Batch (Optional)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.warehousetransfer', verbose_name='Transfer')),
            ],
            options={
                'verbose_name': 'Transfer Item',
                'verbose_name_plural': 'Transfer Items',
                'ordering': ['transfer', 'product__name'],
                'unique_together': {('transfer', 'product', 'batch')},
            },
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['status'], name='inventory_w_status_593e43_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['transfer_date'], name='inventory_w_transfe_b1e858_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['source_warehouse', 'destination_warehouse'], name='inventory_w_source__3a5b1e_idx'),
        ),
    ]
