# Generated by Django 4.2.30 on 2026-05-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_company_warehouse_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='barcode',
            field=models.CharField(blank=True, help_text='Optional barcode for this specific batch. Falls back to batch_number if empty.', max_length=100, null=True, unique=True, verbose_name='Batch Barcode'),
        ),
    ]
