# Generated by Django 4.2.30 on 2026-05-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_batch_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('RETURN_IN', 'Return In (Sale Return)'), ('RETURN_PURCHASE', 'Return Purchase'), ('RETURN_DAMAGED', 'Return Damaged (Quarantine)'), ('RETURN_EXPIRED', 'Return Expired (Quarantine)')], max_length=20, verbose_name='Movement Type'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('PRODUCTION', 'Production'), ('WASTE', 'Waste'), ('EXPIRY', 'Expiry'), ('MANUAL', 'Manual Adjustment')], max_length=20, verbose_name='Reference Type'),
        ),
    ]
