# Generated by Django 4.2.30 on 2026-06-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_batch_location_to_warehouse_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['warehouse'], name='inventory_b_warehou_add691_idx'),
        ),
    ]
