# Generated by Django 4.2.30 on 2026-06-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_batch_inventory_b_warehou_add691_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='batch',
            name='inventory_b_warehou_add691_idx',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='batch',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Location'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['location'], name='inventory_b_locatio_5ba194_idx'),
        ),
    ]
