# Generated by Django 4.2.30 on 2026-06-16 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_company_business_config'),
        ('inventory', '0015_remove_batch_inventory_b_warehou_add691_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='unit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='Company'),
        ),
    ]
