# Generated by Django 4.2.30 on 2026-05-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesinvoice_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='entity',
        ),
        migrations.AddField(
            model_name='customer',
            name='business_license',
            field=models.CharField(blank=True, max_length=50, verbose_name='Business License ( جواز فعالیت )'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact Person Role'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='License Expiry Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='National ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms_days',
            field=models.IntegerField(default=0, verbose_name='Payment Terms (Days)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Registration Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20, verbose_name='Risk Level'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='subtype',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], default='INDIVIDUAL', max_length=20, verbose_name='Party Subtype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('PHARMACY', 'Pharmacy'), ('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('DISTRIBUTOR', 'Distributor'), ('OTHER', 'Other')], default='RETAIL', max_length=20, verbose_name='Customer Category'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['subtype'], name='sales_custo_subtype_69bfae_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status'], name='sales_custo_status_13e5e8_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['risk_level'], name='sales_custo_risk_le_66687c_idx'),
        ),
    ]
