# Generated by Django 4.2.30 on 2026-05-20 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0007_add_payment_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('DISPATCHED', 'Dispatched'), ('PARTIAL_PAID', 'Partial Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('CREDIT_PENDING', 'Credit Pending Approval')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CreditApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Requested Amount')),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Current Balance')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Credit Limit')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('approval_reason', models.TextField(blank=True, verbose_name='Approval Reason')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_credit_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_requests', to='sales.customer', verbose_name='Customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to='sales.salesinvoice', verbose_name='Invoice')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_credit_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Credit Approval Request',
                'verbose_name_plural': 'Credit Approval Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sales_credi_status_31ceab_idx'), models.Index(fields=['customer', 'status'], name='sales_credi_custome_297345_idx')],
            },
        ),
    ]
