# Generated by Django 4.2.30 on 2026-05-24 12:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_add_credit_approval_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='tax_enabled',
            field=models.BooleanField(default=False, help_text='Enable tax calculation for this invoice', verbose_name='Tax Enabled'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate percentage (e.g. 10.00 for 10%%)', max_digits=5, verbose_name='Tax Rate (%)'),
        ),
    ]
