# Generated by Django 4.2.30 on 2026-06-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesinvoice_list_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='salesinvoice',
            name='si_company_created_idx',
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(help_text='Unique sales invoice number per company', max_length=100, verbose_name='Invoice Number'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_number'), name='uniq_sales_invoice_number_per_company'),
        ),
    ]
