# Generated by Django 4.2.30 on 2026-06-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_forensic_audit_fixes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesinvoice',
            name='uniq_sales_invoice_number_per_company',
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(help_text='Unique sales invoice number', max_length=100, unique=True, verbose_name='Invoice Number'),
        ),
    ]
