# Generated by Django 4.2.30 on 2026-05-03 11:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0002_overtime_leave_attendance'),
        ('accounting', '0003_fix_account_category_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Allocation Name')),
                ('allocation_method', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('EQUAL', 'Equal Split'), ('UNITS', 'By Units'), ('REVENUE', 'By Revenue')], default='PERCENTAGE', max_length=20, verbose_name='Allocation Method')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Cost Allocation',
                'verbose_name_plural': 'Cost Allocations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Cost Center Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('cost_center_type', models.CharField(choices=[('DEPARTMENT', 'Department'), ('PROJECT', 'Project'), ('BRANCH', 'Branch'), ('STORE', 'Store'), ('OTHER', 'Other')], default='DEPARTMENT', max_length=20, verbose_name='Type')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Annual Budget')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('manager', models.CharField(blank=True, max_length=255, verbose_name='Manager')),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers', to='accounting.account', verbose_name='Default Expense Account')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers', to='hr.department', verbose_name='Linked Department')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cost_centers.costcenter', verbose_name='Parent Cost Center')),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CostAllocationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of cost to allocate', max_digits=5, verbose_name='Percentage')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cost_centers.costallocation', verbose_name='Allocation')),
                ('target_cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_to', to='cost_centers.costcenter', verbose_name='Target Cost Center')),
            ],
            options={
                'verbose_name': 'Allocation Line',
                'verbose_name_plural': 'Allocation Lines',
            },
        ),
        migrations.AddField(
            model_name='costallocation',
            name='source_cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_from', to='cost_centers.costcenter', verbose_name='Source Cost Center'),
        ),
        migrations.CreateModel(
            name='CostTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cost_centers.costcenter', verbose_name='Cost Center')),
                ('journal_entry_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_transactions', to='accounting.journalentryline', verbose_name='Journal Entry Line')),
            ],
            options={
                'verbose_name': 'Cost Transaction',
                'verbose_name_plural': 'Cost Transactions',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['cost_center', 'transaction_date'], name='cost_center_cost_ce_941d32_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['cost_center_type'], name='cost_center_cost_ce_aef9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['is_active'], name='cost_center_is_acti_b9cd28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costallocationline',
            unique_together={('allocation', 'target_cost_center')},
        ),
    ]
