# Generated by Django 4.2.30 on 2026-05-19 01:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0002_overtime_leave_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0006_salesinvoice_created_by'),
        ('inventory', '0012_stockmovement_created_by'),
        ('accounting', '0008_add_return_entry_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(max_length=50, unique=True, verbose_name='Claim Number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('VOIDED', 'Voided')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total invoice amount (before insurance)', max_digits=12, verbose_name='Total Amount')),
                ('covered_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount insurance will cover', max_digits=12, verbose_name='Covered Amount')),
                ('patient_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount patient must pay', max_digits=12, verbose_name='Patient Amount')),
                ('deductible_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Deductible Applied')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims', to='sales.salesinvoice', verbose_name='Sales Invoice')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims', to='accounting.journalentry', verbose_name='Journal Entry')),
            ],
            options={
                'verbose_name': 'Insurance Claim',
                'verbose_name_plural': 'Insurance Claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Provider Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Provider Code')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Insurance Provider',
                'verbose_name_plural': 'Insurance Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(max_length=100, unique=True, verbose_name='Policy Number')),
                ('policy_type', models.CharField(choices=[('HEALTH', 'Health Insurance'), ('PHARMACY', 'Pharmacy Insurance'), ('MEDICARE', 'Medicare'), ('PRIVATE', 'Private Insurance'), ('GOVERNMENT', 'Government Scheme'), ('OTHER', 'Other')], default='PHARMACY', max_length=20, verbose_name='Policy Type')),
                ('coverage_type', models.CharField(choices=[('FULL', 'Full Coverage'), ('PARTIAL', 'Partial Coverage'), ('LIMITED', 'Limited Coverage')], default='PARTIAL', max_length=20, verbose_name='Coverage Type')),
                ('coverage_percentage', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Percentage of eligible costs covered by insurance', max_digits=5, verbose_name='Coverage Percentage (%)')),
                ('annual_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum annual coverage amount. 0 = unlimited', max_digits=12, verbose_name='Annual Limit')),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already claimed this period', max_digits=12, verbose_name='Used Amount')),
                ('deductible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount patient must pay before coverage kicks in', max_digits=10, verbose_name='Deductible')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_policies', to='sales.customer', verbose_name='Customer/Patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurance.insuranceprovider', verbose_name='Insurance Provider')),
            ],
            options={
                'verbose_name': 'Insurance Policy',
                'verbose_name_plural': 'Insurance Policies',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClaimItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Price')),
                ('covered_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Covered Amount')),
                ('patient_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Patient Amount')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Is Approved')),
                ('rejection_note', models.TextField(blank=True, verbose_name='Rejection Note')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='insurance.claim', verbose_name='Claim')),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claim_items', to='sales.salesitem', verbose_name='Invoice Item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Claim Item',
                'verbose_name_plural': 'Claim Items',
            },
        ),
        migrations.CreateModel(
            name='ClaimApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('SUBMIT', 'Submitted'), ('APPROVE', 'Approved'), ('PARTIAL_APPROVE', 'Partially Approved'), ('REJECT', 'Rejected'), ('PAY', 'Paid'), ('VOID', 'Voided')], max_length=20, verbose_name='Action')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='insurance.claim', verbose_name='Claim')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee', verbose_name='Performed By')),
            ],
            options={
                'verbose_name': 'Claim Approval',
                'verbose_name_plural': 'Claim Approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance.insurancepolicy', verbose_name='Insurance Policy'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['policy_number'], name='insurance_i_policy__526337_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['customer', 'is_active'], name='insurance_i_custome_e69b76_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_number'], name='insurance_c_claim_n_9e828c_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['policy', 'status'], name='insurance_c_policy__acf620_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['invoice'], name='insurance_c_invoice_e1fce3_idx'),
        ),
    ]
