# Generated by Django 4.2.30 on 2026-05-02 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_warehouse_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('STOCK_LOW', 'Low Stock Alert'), ('STOCK_EXPIRY', 'Expiring Batch Alert'), ('STOCK_OUT', 'Out of Stock Alert'), ('ACTIVITY_LOGIN', 'User Login'), ('ACTIVITY_LOGOUT', 'User Logout'), ('ACTIVITY_CREATE', 'Record Created'), ('ACTIVITY_UPDATE', 'Record Updated'), ('ACTIVITY_DELETE', 'Record Deleted'), ('SYSTEM', 'System Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventory.batch')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'security_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='security_no_user_id_98730c_idx'), models.Index(fields=['notification_type', 'created_at'], name='security_no_notific_daf5fe_idx'), models.Index(fields=['user', 'notification_type'], name='security_no_user_id_95e5d5_idx')],
            },
        ),
    ]
