# Generated by Django 4.2.30 on 2026-05-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_add_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
