# Generated by Django 4.2.30 on 2026-05-17 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0004_add_2fa_and_password_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jti', models.CharField(db_index=True, help_text='JWT ID claim', max_length=255, unique=True)),
                ('token_type', models.CharField(choices=[('access', 'Access'), ('refresh', 'Refresh')], default='access', max_length=10)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Original token expiry — used for cleanup')),
                ('reason', models.CharField(blank=True, choices=[('logout', 'User logout'), ('password_change', 'Password changed'), ('admin_revoke', 'Admin revocation'), ('security_event', 'Security event')], default='', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revoked_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revoked Token',
                'verbose_name_plural': 'Revoked Tokens',
                'db_table': 'security_revoked_token',
                'ordering': ['-revoked_at'],
                'indexes': [models.Index(fields=['expires_at'], name='security_re_expires_b78771_idx'), models.Index(fields=['user', 'revoked_at'], name='security_re_user_id_551adf_idx')],
            },
        ),
    ]
