# Generated by Django 4.2.30 on 2026-05-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_add_revoked_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='token',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='token_hash',
            field=models.CharField(db_index=True, default='', help_text='SHA-256 hash of the actual token', max_length=64, unique=True),
        ),
    ]
