# Generated by Django 4.2.30 on 2026-05-03 10:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('code', models.CharField(help_text='Unique code for the category (e.g., COMP, FURN, VEHI)', max_length=20, unique=True, verbose_name='Category Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('default_useful_life_months', models.PositiveIntegerField(default=60, help_text='Default useful life in months for assets in this category', verbose_name='Default Useful Life (Months)')),
                ('default_depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight Line'), ('DECLINING_BALANCE', 'Declining Balance')], default='STRAIGHT_LINE', max_length=20, verbose_name='Default Depreciation Method')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('asset_code', models.CharField(help_text='Unique identifier for the asset', max_length=50, unique=True, verbose_name='Asset Code')),
                ('asset_name', models.CharField(max_length=255, verbose_name='Asset Name')),
                ('serial_number', models.CharField(blank=True, help_text='Manufacturer serial number', max_length=100, verbose_name='Serial Number')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('purchase_cost', models.DecimalField(decimal_places=2, help_text='Original purchase cost including any additional costs', max_digits=15, verbose_name='Purchase Cost')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated value at the end of useful life', max_digits=15, verbose_name='Salvage Value')),
                ('useful_life_months', models.PositiveIntegerField(help_text='Total useful life in months', verbose_name='Useful Life (Months)')),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight Line'), ('DECLINING_BALANCE', 'Declining Balance')], default='STRAIGHT_LINE', max_length=20, verbose_name='Depreciation Method')),
                ('current_book_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current book value after depreciation', max_digits=15, verbose_name='Current Book Value')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total depreciation taken to date', max_digits=15, verbose_name='Accumulated Depreciation')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('FULLY_DEPRECIATED', 'Fully Depreciated'), ('DISPOSED', 'Disposed')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('location', models.CharField(blank=True, help_text='Physical location of the asset', max_length=255, verbose_name='Location')),
                ('responsible_person', models.CharField(blank=True, help_text='Person responsible for the asset', max_length=255, verbose_name='Responsible Person')),
                ('depreciation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Custom depreciation rate for declining balance method', max_digits=5, null=True, verbose_name='Depreciation Rate (%)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='fixed_assets.assetcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('disposal_date', models.DateField(verbose_name='Disposal Date')),
                ('disposal_method', models.CharField(choices=[('SOLD', 'Sold'), ('SCRAPPED', 'Scrapped'), ('DONATED', 'Donated'), ('EXCHANGED', 'Exchanged'), ('LOST', 'Lost/Stolen')], max_length=20, verbose_name='Disposal Method')),
                ('proceeds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount received from disposal (0 if scrapped/donated)', max_digits=15, verbose_name='Proceeds')),
                ('disposal_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost incurred for disposal', max_digits=15, verbose_name='Disposal Cost')),
                ('gain_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated gain or loss on disposal', max_digits=15, verbose_name='Gain/Loss')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('buyer_info', models.CharField(blank=True, help_text='Name/contact of buyer if sold', max_length=255, verbose_name='Buyer Information')),
                ('reference_number', models.CharField(blank=True, help_text='Disposal reference document number', max_length=100, verbose_name='Reference Number')),
                ('is_posted', models.BooleanField(default=False, help_text='Posted disposal is reflected in financial statements', verbose_name='Is Posted')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='fixed_assets.fixedasset', verbose_name='Fixed Asset')),
            ],
            options={
                'verbose_name': 'Asset Disposal',
                'verbose_name_plural': 'Asset Disposals',
                'ordering': ['-disposal_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Depreciation Amount')),
                ('book_value_start', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Book Value at Start of Period')),
                ('book_value_end', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Book Value at End of Period')),
                ('is_posted', models.BooleanField(default=False, help_text='Posted depreciation is included in financial statements', verbose_name='Is Posted')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciations', to='fixed_assets.fixedasset', verbose_name='Fixed Asset')),
            ],
            options={
                'verbose_name': 'Asset Depreciation',
                'verbose_name_plural': 'Asset Depreciations',
                'ordering': ['-period_end'],
            },
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['asset_code'], name='fixed_asset_asset_c_30c0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['status'], name='fixed_asset_status_a0b8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['category'], name='fixed_asset_categor_32ceb0_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['purchase_date'], name='fixed_asset_purchas_e65f55_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdisposal',
            index=models.Index(fields=['asset'], name='fixed_asset_asset_i_e8d12a_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdisposal',
            index=models.Index(fields=['disposal_date'], name='fixed_asset_disposa_a9f40d_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdisposal',
            index=models.Index(fields=['is_posted'], name='fixed_asset_is_post_a7c4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdepreciation',
            index=models.Index(fields=['asset'], name='fixed_asset_asset_i_9afb94_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdepreciation',
            index=models.Index(fields=['period_start'], name='fixed_asset_period__38d6be_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdepreciation',
            index=models.Index(fields=['period_end'], name='fixed_asset_period__51fd38_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdepreciation',
            index=models.Index(fields=['is_posted'], name='fixed_asset_is_post_9b837d_idx'),
        ),
    ]
