# Generated by Django 4.2.30 on 2026-05-07 05:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_invoicetemplate'),
        ('accounting', '0006_account_company_journalentry_company'),
        ('payments', '0002_alter_financialtransaction_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_number', models.CharField(max_length=50, unique=True, verbose_name='Expense #')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('payee', models.CharField(blank=True, help_text='Who was paid?', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='Company')),
                ('expense_account', models.ForeignKey(limit_choices_to={'account_type': 'EXPENSE'}, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_expenses', to='accounting.account')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_expenses', to='accounting.journalentry')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_expenses', to='payments.paymentaccount')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
