# Generated by Django 4.2.30 on 2026-06-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(max_length=50, verbose_name='Expense #'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('company', 'expense_number'), name='uniq_expense_number_per_company'),
        ),
    ]
