# Generated by Django 4.2.30 on 2026-06-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_forensic_audit_fixes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expense',
            name='uniq_expense_number_per_company',
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Expense #'),
        ),
    ]
