# Generated by Django 4.2.30 on 2026-04-29 15:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_fix_account_category_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Account Code')),
                ('account_type', models.CharField(choices=[('CASH', 'Cash Account'), ('BANK', 'Bank Account'), ('MOBILE_WALLET', 'Mobile Wallet'), ('HAWALA', 'Hawala Account'), ('CHEQUE', 'Cheque Account')], max_length=20, verbose_name='Account Type')),
                ('provider_name', models.CharField(blank=True, help_text='Bank name, mobile operator, hawala dealer', max_length=100, verbose_name='Provider Name')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Account Number')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('swift_code', models.CharField(blank=True, max_length=11, verbose_name='SWIFT/BIC Code')),
                ('currency', models.CharField(choices=[('AFN', 'Afghan Afghani'), ('USD', 'US Dollar'), ('PKR', 'Pakistani Rupee'), ('IRR', 'Iranian Rial')], default='AFN', max_length=3, verbose_name='Account Currency')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Current Balance')),
                ('min_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Minimum Balance Alert')),
                ('max_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Maximum Balance Limit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('location', models.CharField(blank=True, help_text='e.g., Counter 1, Main Office, Branch 2', max_length=100, verbose_name='Location')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('accounting_account', models.ForeignKey(help_text='Account in the chart of accounts', on_delete=django.db.models.deletion.PROTECT, related_name='payment_accounts', to='accounting.account', verbose_name='Linked Accounting Account')),
            ],
            options={
                'verbose_name': 'Payment Account',
                'verbose_name_plural': 'Payment Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TransactionSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('settlement_number', models.CharField(max_length=50, unique=True, verbose_name='Settlement Number')),
                ('settlement_type', models.CharField(choices=[('BATCH', 'Batch Settlement'), ('BANK_RECONCILIATION', 'Bank Reconciliation'), ('HAWALA_SETTLEMENT', 'Hawala Settlement'), ('MOBILE_SETTLEMENT', 'Mobile Money Settlement'), ('MANUAL', 'Manual Settlement')], max_length=30, verbose_name='Settlement Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DISCREPANCY', 'Discrepancy'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Expected Amount')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Actual Amount')),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Difference')),
                ('external_reference', models.CharField(blank=True, help_text='Bank statement ref, hawala settlement ref', max_length=100, verbose_name='External Reference')),
                ('description', models.TextField(verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('performed_by', models.CharField(blank=True, max_length=255, verbose_name='Performed By')),
                ('approved_by', models.CharField(blank=True, max_length=255, verbose_name='Approved By')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='payments.paymentaccount', verbose_name='Payment Account')),
            ],
            options={
                'verbose_name': 'Transaction Settlement',
                'verbose_name_plural': 'Transaction Settlements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Payment Method Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Method Code')),
                ('method_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('HAWALA', 'Hawala'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('MIXED', 'Mixed Payment')], max_length=20, verbose_name='Method Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('provider_name', models.CharField(blank=True, help_text='e.g., M-Pesa, Etisalat, Al-Farooq Hawala', max_length=100, verbose_name='Provider Name')),
                ('provider_code', models.CharField(blank=True, max_length=50, verbose_name='Provider Code')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transaction fee as percentage (e.g., 1.5 for 1.5%)', max_digits=5, verbose_name='Fee Percentage')),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Fixed Fee')),
                ('ref_prefix', models.CharField(blank=True, help_text='Prefix for auto-generated transaction numbers', max_length=10, verbose_name='Reference Prefix')),
                ('ref_format', models.CharField(blank=True, help_text='Format pattern for transaction references', max_length=50, verbose_name='Reference Format')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['method_type'], name='payments_pa_method__c479ee_idx'), models.Index(fields=['is_active'], name='payments_pa_is_acti_c01362_idx'), models.Index(fields=['is_default'], name='payments_pa_is_defa_9c26a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('transaction_number', models.CharField(help_text='Auto-generated unique transaction reference', max_length=50, unique=True, verbose_name='Transaction Number')),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment'), ('REFUND', 'Refund')], max_length=20, verbose_name='Transaction Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], default='COMPLETED', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('currency', models.CharField(default='AFN', max_length=3, verbose_name='Currency')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Transaction Fee')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount after deducting fees', max_digits=15, null=True, verbose_name='Net Amount')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=15, verbose_name='Exchange Rate')),
                ('amount_in_base', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Amount in Base Currency (AFN)')),
                ('reference_number', models.CharField(blank=True, help_text='Mobile payment ref, hawala ref, bank ref', max_length=100, verbose_name='External Reference')),
                ('internal_reference', models.CharField(blank=True, max_length=100, verbose_name='Internal Reference')),
                ('description', models.TextField(verbose_name='Description')),
                ('party_type', models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('EMPLOYEE', 'Employee'), ('OTHER', 'Other')], max_length=20, verbose_name='Party Type')),
                ('party_id', models.UUIDField(blank=True, null=True, verbose_name='Party ID')),
                ('party_name', models.CharField(blank=True, max_length=255, verbose_name='Party Name')),
                ('invoice_type', models.CharField(blank=True, choices=[('SALES', 'Sales Invoice'), ('PURCHASE', 'Purchase Invoice')], max_length=20, verbose_name='Invoice Type')),
                ('invoice_id', models.UUIDField(blank=True, null=True, verbose_name='Invoice ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, verbose_name='Transaction Date')),
                ('value_date', models.DateField(blank=True, help_text='Date when funds are actually available', null=True, verbose_name='Value Date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('hawala_dealer', models.CharField(blank=True, max_length=200, verbose_name='Hawala Dealer')),
                ('hawala_token', models.CharField(blank=True, help_text='Secret code for hawala collection', max_length=50, verbose_name='Hawala Token/Code')),
                ('hawala_origin', models.CharField(blank=True, help_text='City/country of origin', max_length=100, verbose_name='Hawala Origin')),
                ('hawala_destination', models.CharField(blank=True, help_text='City/country of destination', max_length=100, verbose_name='Hawala Destination')),
                ('mobile_number', models.CharField(blank=True, max_length=20, verbose_name='Mobile Number')),
                ('mobile_operator', models.CharField(blank=True, max_length=100, verbose_name='Mobile Operator')),
                ('is_settled', models.BooleanField(default=False, help_text='Whether the transaction has been reconciled', verbose_name='Is Settled')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='Settled At')),
                ('settlement_reference', models.CharField(blank=True, max_length=100, verbose_name='Settlement Reference')),
                ('journal_entry_id', models.UUIDField(blank=True, null=True, verbose_name='Journal Entry ID')),
                ('performed_by', models.CharField(blank=True, max_length=255, verbose_name='Performed By')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('destination_account', models.ForeignKey(blank=True, help_text='Account money is going to (for receipts/transfers)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='payments.paymentaccount', verbose_name='Destination Account')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymentmethod', verbose_name='Payment Method')),
                ('source_account', models.ForeignKey(blank=True, help_text='Account money is coming from (for payments/transfers)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='payments.paymentaccount', verbose_name='Source Account')),
            ],
            options={
                'verbose_name': 'Financial Transaction',
                'verbose_name_plural': 'Financial Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('included_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Included Amount')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.transactionsettlement', verbose_name='Settlement')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='payments.financialtransaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Settlement Transaction',
                'verbose_name_plural': 'Settlement Transactions',
                'unique_together': {('settlement', 'transaction')},
            },
        ),
        migrations.AddIndex(
            model_name='paymentaccount',
            index=models.Index(fields=['account_type'], name='payments_pa_account_43a15a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentaccount',
            index=models.Index(fields=['currency'], name='payments_pa_currenc_ee66c2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentaccount',
            index=models.Index(fields=['is_active'], name='payments_pa_is_acti_e1bd01_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_number'], name='payments_fi_transac_bc7339_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_type', 'status'], name='payments_fi_transac_8a4446_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_date'], name='payments_fi_transac_388bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['payment_method'], name='payments_fi_payment_1d1a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['source_account'], name='payments_fi_source__25df8b_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['destination_account'], name='payments_fi_destina_6b9655_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['invoice_type', 'invoice_id'], name='payments_fi_invoice_48c872_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['party_type', 'party_id'], name='payments_fi_party_t_3f7b59_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['is_settled'], name='payments_fi_is_sett_b15381_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['reference_number'], name='payments_fi_referen_ab9544_idx'),
        ),
    ]
