# Generated by Django 4.2.30 on 2026-06-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_financialtransaction_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementtransaction',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.transactionsettlement', verbose_name='Settlement'),
        ),
    ]
