# Generated by Django 6.0.6 on 2026-06-18 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_financialtransaction_company_paymentaccount_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialtransaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='company',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='company',
        ),
        migrations.RemoveField(
            model_name='transactionsettlement',
            name='company',
        ),
        migrations.AlterField(
            model_name='settlementtransaction',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.transactionsettlement', verbose_name='Settlement'),
        ),
    ]
