# Generated by Django 4.2.30 on 2026-05-06 12:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_usercompanymapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('report_generation', 'Report Generation'), ('export_generation', 'Export Generation'), ('financial_reconciliation', 'Financial Reconciliation'), ('anomaly_scan', 'Anomaly Scan'), ('inventory_expiry_scan', 'Inventory Expiry Scan'), ('notification_dispatch', 'Notification Dispatch'), ('backup_validation', 'Backup Validation'), ('cleanup_task', 'Cleanup Task'), ('workflow_notification', 'Workflow Notification'), ('overdue_scan', 'Overdue Scan')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('CANCELLED', 'Cancelled'), ('STUCK', 'Stuck')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='NORMAL', max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='Job input data')),
                ('result', models.JSONField(default=dict, help_text='Job output data')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('recurring_id', models.CharField(blank=True, help_text='ID for recurring jobs', max_length=50)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Key to prevent duplicate execution', max_length=100)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_jobs', to='core.company')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'background_job',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('job_type', models.CharField(choices=[('report_generation', 'Report Generation'), ('export_generation', 'Export Generation'), ('financial_reconciliation', 'Financial Reconciliation'), ('anomaly_scan', 'Anomaly Scan'), ('inventory_expiry_scan', 'Inventory Expiry Scan'), ('notification_dispatch', 'Notification Dispatch'), ('backup_validation', 'Backup Validation'), ('cleanup_task', 'Cleanup Task'), ('workflow_notification', 'Workflow Notification'), ('overdue_scan', 'Overdue Scan')], max_length=50)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('run_time', models.CharField(default='00:00', max_length=5)),
                ('day_of_week', models.PositiveIntegerField(blank=True, null=True)),
                ('day_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('default_payload', models.JSONField(default=dict)),
                ('max_retries', models.PositiveIntegerField(default=3)),
            ],
            options={
                'db_table': 'scheduled_task',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('duration_seconds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='jobs.backgroundjob')),
            ],
            options={
                'db_table': 'job_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='job_audit_l_job_id_ba59d4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='backgroundjob',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='background__status_4e087e_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundjob',
            index=models.Index(fields=['job_type', 'status'], name='background__job_typ_1c0378_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundjob',
            index=models.Index(fields=['scheduled_for', 'is_scheduled'], name='background__schedul_669757_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundjob',
            index=models.Index(fields=['company', 'status'], name='background__company_83d81f_idx'),
        ),
    ]
