# Generated by Django 4.2.30 on 2026-05-03 11:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_fix_account_category_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Forecast Name')),
                ('forecast_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20, verbose_name='Forecast Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Cash Flow Forecast',
                'verbose_name_plural': 'Cash Flow Forecasts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Scenario Name')),
                ('scenario_type', models.CharField(choices=[('OPTIMISTIC', 'Optimistic'), ('REALISTIC', 'Realistic'), ('PESSIMISTIC', 'Pessimistic'), ('CUSTOM', 'Custom')], max_length=20, verbose_name='Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('sales_growth_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Sales Growth Rate %')),
                ('collection_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Collection Rate %')),
                ('payment_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Payment Rate %')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Cash Flow Scenario',
                'verbose_name_plural': 'Cash Flow Scenarios',
            },
        ),
        migrations.CreateModel(
            name='CashFlowItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.CharField(choices=[('SALES_RECEIPT', 'Sales Receipt'), ('ACCOUNTS_RECEIVABLE', 'Accounts Receivable'), ('OTHER_INCOME', 'Other Income'), ('INVENTORY_PAYMENT', 'Inventory Payment'), ('ACCOUNTS_PAYABLE', 'Accounts Payable'), ('PAYROLL', 'Payroll'), ('OPERATING_EXPENSE', 'Operating Expense'), ('CAPITAL_EXPENDITURE', 'Capital Expenditure'), ('TAX_PAYMENT', 'Tax Payment'), ('LOAN_PAYMENT', 'Loan Payment'), ('OTHER_EXPENSE', 'Other Expense')], max_length=30, verbose_name='Category')),
                ('item_type', models.CharField(choices=[('INFLOW', 'Inflow'), ('OUTFLOW', 'Outflow')], max_length=10, verbose_name='Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('expected_date', models.DateField(verbose_name='Expected Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('probability', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Probability %')),
                ('is_actual', models.BooleanField(default=False, verbose_name='Is Actual')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Actual Date')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Actual Amount')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cashflow.cashflowforecast', verbose_name='Forecast')),
            ],
            options={
                'verbose_name': 'Cash Flow Item',
                'verbose_name_plural': 'Cash Flow Items',
                'ordering': ['expected_date'],
                'indexes': [models.Index(fields=['expected_date'], name='cashflow_ca_expecte_0ae82e_idx'), models.Index(fields=['category'], name='cashflow_ca_categor_5a1bf0_idx')],
            },
        ),
    ]
