# Generated by Django 4.2.30 on 2026-05-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollcycle',
            name='accounting_entry_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
