# Generated by Django 4.2.30 on 2026-05-03 11:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_fix_account_category_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Entity Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Entity Code')),
                ('entity_type', models.CharField(choices=[('HEADQUARTER', 'Headquarters'), ('PHARMACY', 'Pharmacy'), ('WAREHOUSE', 'Warehouse'), ('DISTRIBUTION_CENTER', 'Distribution Center'), ('OFFICE', 'Office')], default='PHARMACY', max_length=20, verbose_name='Entity Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Entity')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='Tax Number')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='License Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('base_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='accounting.currency', verbose_name='Base Currency')),
            ],
            options={
                'verbose_name': 'Business Entity',
                'verbose_name_plural': 'Business Entities',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InterCompanyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'Stock Transfer'), ('LOAN', 'Loan/Advance'), ('EXPENSE', 'Expense Reimbursement'), ('SERVICE', 'Service Fee')], max_length=20, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference Number')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Is Reconciled')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.currency', verbose_name='Currency')),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sent', to='entities.entity', verbose_name='From Entity')),
                ('to_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to='entities.entity', verbose_name='To Entity')),
            ],
            options={
                'verbose_name': 'Inter-Company Transaction',
                'verbose_name_plural': 'Inter-Company Transactions',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['from_entity', 'to_entity'], name='entities_in_from_en_6d27fb_idx'), models.Index(fields=['transaction_date'], name='entities_in_transac_0d0a0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('account_name', models.CharField(blank=True, help_text='Custom name for this entity (e.g., Main Pharmacy Cash)', max_length=255, verbose_name='Entity Account Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_mappings', to='accounting.account', verbose_name='Account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='entities.entity', verbose_name='Entity')),
            ],
            options={
                'verbose_name': 'Entity Account',
                'verbose_name_plural': 'Entity Accounts',
                'unique_together': {('entity', 'account')},
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['entity_type'], name='entities_en_entity__73cf99_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['is_active'], name='entities_en_is_acti_051fb8_idx'),
        ),
    ]
