"""
Phase 5B.3 — Immutable Append-Only Event Store.

The foundational data store for the Digital Twin.
ALL system state must be derived from events in this store.

Core principle:
    "If it is not in the Event Store, it did not happen."

Properties:
- Append-only: events can only be added, never modified or deleted
- Immutable: once stored, an event never changes
- Deterministic: replay produces identical state
- Time-ordered: events have monotonic sequence numbers
- Queryable: by domain, aggregate_id, source_type, time range
"""
import hashlib
import json
import logging
from collections import defaultdict
from datetime import datetime
from typing import Any, Dict, List, Optional, Set, Tuple
from uuid import uuid4

from core.operations.truth.models import (
    Event, SourceType, Domain, ConsistencyResult,
    TRUTH_MODELS_VERSION,
)

logger = logging.getLogger('erp.truth.event_store')

EVENT_STORE_VERSION = "1.0.0"
MAX_EVENTS_IN_MEMORY = 100000


class EventStore:
    """Immutable, append-only event store with bounded memory.

    This is the SINGLE SOURCE OF TRUTH for all Digital Twin state.
    No data exists in the Digital Twin unless it originated from this store.
    """

    def __init__(self, max_events: int = MAX_EVENTS_IN_MEMORY):
        self._events: List[Event] = []
        self._max_events = max_events
        self._by_id: Dict[str, Event] = {}
        self._by_domain: Dict[str, List[Event]] = defaultdict(list)
        self._by_aggregate: Dict[str, List[Event]] = defaultdict(list)
        self._by_source_type: Dict[str, List[Event]] = defaultdict(list)
        self._by_event_type: Dict[str, List[Event]] = defaultdict(list)
        self._sequences: Dict[str, int] = defaultdict(int)

    def append(self, event: Event) -> str:
        """Append an event to the store. Returns event_id.

        Deterministic — same event content produces same event_id
        (assuming same event_id, which is generated by caller).

        Raises:
            ValueError: If an event with this event_id already exists.
        """
        if event.event_id in self._by_id:
            raise ValueError(f"Duplicate event_id: {event.event_id}")

        if len(self._events) >= self._max_events:
            removed = self._events.pop(0)
            self._by_id.pop(removed.event_id, None)
            key = f"{removed.domain.value}:{removed.aggregate_id}"
            seq_key = f"{removed.source_type.value}:{removed.domain.value}:{removed.aggregate_id}"

        self._events.append(event)
        self._by_id[event.event_id] = event
        self._by_domain[event.domain.value].append(event)
        agg_key = f"{event.domain.value}:{event.aggregate_id}"
        self._by_aggregate[agg_key].append(event)
        self._by_source_type[event.source_type.value].append(event)
        self._by_event_type[event.event_type].append(event)

        seq_key = f"{event.source_type.value}:{event.domain.value}:{event.aggregate_id}"
        self._sequences[seq_key] = max(self._sequences[seq_key], event.sequence)

        return event.event_id

    def get(self, event_id: str) -> Optional[Event]:
        """Get an event by ID."""
        return self._by_id.get(event_id)

    def get_by_domain(self, domain: Domain) -> List[Event]:
        """Get all events for a domain, in append order."""
        return list(self._by_domain.get(domain.value, []))

    def get_by_aggregate(self, domain: Domain, aggregate_id: str) -> List[Event]:
        """Get all events for a specific aggregate, ordered by sequence."""
        key = f"{domain.value}:{aggregate_id}"
        return sorted(
            self._by_aggregate.get(key, []),
            key=lambda e: e.sequence,
        )

    def get_by_source_type(self, source_type: SourceType) -> List[Event]:
        """Get events by source type."""
        return list(self._by_source_type.get(source_type.value, []))

    def get_by_event_type(self, event_type: str) -> List[Event]:
        """Get events by event type."""
        return list(self._by_event_type.get(event_type, []))

    def get_by_time_range(self, start: str, end: str) -> List[Event]:
        """Get events within a time range (inclusive)."""
        return [
            e for e in self._events
            if start <= e.timestamp <= end
        ]

    def get_all(self) -> List[Event]:
        """Get all events in append order."""
        return list(self._events)

    def count(self) -> int:
        return len(self._events)

    def count_by_domain(self) -> Dict[str, int]:
        return {d: len(evts) for d, evts in self._by_domain.items()}

    def count_by_source(self) -> Dict[str, int]:
        return {s: len(evts) for s, evts in self._by_source_type.items()}

    def get_last_sequence(self, source_type: SourceType, domain: Domain, aggregate_id: str) -> int:
        """Get the last sequence number for an aggregate."""
        seq_key = f"{source_type.value}:{domain.value}:{aggregate_id}"
        return self._sequences.get(seq_key, 0)

    def event_exists(self, event_id: str) -> bool:
        """Check if an event exists in the store by ID."""
        return event_id in self._by_id

    def verify_event_chain(
        self,
        domain: Domain,
        aggregate_id: str,
        expected_count: int,
    ) -> Tuple[bool, List[str], List[str]]:
        """Verify that an aggregate has the expected number of events.

        Returns:
            (is_valid, existing_event_ids, missing_descriptions)
        """
        events = self.get_by_aggregate(domain, aggregate_id)
        actual_count = len(events)
        if actual_count >= expected_count:
            return True, [e.event_id for e in events], []
        missing = expected_count - actual_count
        return (
            False,
            [e.event_id for e in events],
            [f"missing {missing} event(s) for aggregate {aggregate_id}"],
        )

    def check_sequence_continuity(self, domain: Domain) -> List[Dict[str, Any]]:
        """Check for gaps in event sequences per aggregate."""
        gaps = []
        for agg_key, events in self._by_aggregate.items():
            if not agg_key.startswith(domain.value):
                continue
            sorted_events = sorted(events, key=lambda e: e.sequence)
            for i in range(len(sorted_events) - 1):
                expected = sorted_events[i].sequence + 1
                actual = sorted_events[i + 1].sequence
                if actual != expected:
                    gaps.append({
                        "aggregate_id": sorted_events[i].aggregate_id,
                        "expected_sequence": expected,
                        "actual_sequence": actual,
                        "gap_size": actual - expected,
                        "prev_event_id": sorted_events[i].event_id,
                        "next_event_id": sorted_events[i + 1].event_id,
                    })
        return gaps

    def run_consistency_check(self) -> ConsistencyResult:
        """Run a full consistency check on the Event Store.

        Verifies:
        - Total event counts
        - Distribution by domain and source
        - Sequence continuity
        - Timestamp ordering
        """
        all_events = self._events
        gaps = self.check_sequence_continuity(Domain.INVENTORY)
        gaps.extend(self.check_sequence_continuity(Domain.ACCOUNTING))
        gaps.extend(self.check_sequence_continuity(Domain.HR))
        gaps.extend(self.check_sequence_continuity(Domain.SALES_PURCHASE))
        gaps.extend(self.check_sequence_continuity(Domain.FIXED_ASSETS))

        timestamp_issues = []
        for i in range(len(all_events) - 1):
            if all_events[i].timestamp > all_events[i + 1].timestamp:
                timestamp_issues.append(
                    f"Timestamp inversion at {all_events[i].event_id} → {all_events[i + 1].event_id}"
                )

        return ConsistencyResult(
            consistent=len(gaps) == 0 and len(timestamp_issues) == 0,
            total_events=len(all_events),
            events_by_domain=self.count_by_domain(),
            events_by_source=self.count_by_source(),
            sequence_gaps=gaps,
            timestamp_anomalies=timestamp_issues,
        )

    def compute_state_hash(self) -> str:
        """Compute a deterministic hash of the entire event store state.

        Used for projection integrity verification.
        """
        h = hashlib.sha256()
        for event in self._events:
            h.update(event.event_id.encode())
            h.update(event.event_type.encode())
            h.update(str(event.sequence).encode())
        return h.hexdigest()

    def clear(self) -> None:
        """Clear all events. For testing only."""
        self._events.clear()
        self._by_id.clear()
        self._by_domain.clear()
        self._by_aggregate.clear()
        self._by_source_type.clear()
        self._by_event_type.clear()
        self._sequences.clear()

    def rebuild_from_list(self, events: List[Event]) -> None:
        """Rebuild store from a list of events. For replay reconstruction."""
        self.clear()
        for event in sorted(events, key=lambda e: (e.timestamp, e.sequence)):
            self.append(event)


class EventFactory:
    """Factory for creating deterministic events.

    Ensures all events are created with correct structure.
    """

    @staticmethod
    def create_event(
        source_type: SourceType,
        domain: Domain,
        event_type: str,
        aggregate_id: str,
        payload: Dict[str, Any],
        metadata: Optional[Dict[str, Any]] = None,
        timestamp: Optional[str] = None,
        sequence: Optional[int] = None,
    ) -> Event:
        """Create a deterministic event.

        Args:
            source_type: REAL, SIMULATION, or MANUAL.
            domain: The domain this event belongs to.
            event_type: Canonical event type name.
            aggregate_id: The domain entity ID.
            payload: Structured event data.
            metadata: Optional metadata.
            timestamp: ISO timestamp (auto-generated if None).
            sequence: Sequence number (auto if None, but should be set by caller).

        Returns:
            An immutable Event.
        """
        if timestamp is None:
            timestamp = datetime.utcnow().isoformat() + "Z"
        if sequence is None:
            sequence = 0

        return Event(
            source_type=source_type,
            domain=domain,
            event_type=event_type,
            aggregate_id=aggregate_id,
            timestamp=timestamp,
            sequence=sequence,
            payload=payload,
            metadata={
                "factory_version": TRUTH_MODELS_VERSION,
                "created_by": "EventFactory",
                **(metadata or {}),
            },
        )


_global_store: Optional[EventStore] = None


def get_event_store() -> EventStore:
    global _global_store
    if _global_store is None:
        _global_store = EventStore()
    return _global_store


def reset_event_store() -> None:
    global _global_store
    _global_store = None
