# Generated by Django 4.2.30 on 2026-05-03 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Policy Name')),
                ('app_labels', models.JSONField(default=list, verbose_name='App Labels')),
                ('action_types', models.JSONField(default=list, verbose_name='Action Types')),
                ('retention_days', models.IntegerField(verbose_name='Retention Days')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Audit Retention Policy',
                'verbose_name_plural': 'Audit Retention Policies',
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REVERSE', 'Reverse'), ('CANCEL', 'Cancel')], max_length=20, verbose_name='Action')),
                ('app_label', models.CharField(max_length=50, verbose_name='App')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='Object ID')),
                ('object_repr', models.TextField(blank=True, verbose_name='Object Representation')),
                ('changes', models.JSONField(default=dict, verbose_name='Field Changes')),
                ('old_values', models.JSONField(default=dict, verbose_name='Old Values')),
                ('new_values', models.JSONField(default=dict, verbose_name='New Values')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='Request Method')),
                ('request_path', models.TextField(blank=True, verbose_name='Request Path')),
                ('is_error', models.BooleanField(default=False, verbose_name='Is Error')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('execution_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Execution Time (ms)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trail_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audit Trails',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='audit_audit_user_id_b5c4c3_idx'), models.Index(fields=['app_label', 'model_name'], name='audit_audit_app_lab_8fe14e_idx'), models.Index(fields=['created_at'], name='audit_audit_created_83821c_idx'), models.Index(fields=['object_id'], name='audit_audit_object__24de5c_idx')],
            },
        ),
    ]
