# Generated by Django 4.2.30 on 2026-05-03 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_multitenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(blank=True, default='', help_text='Role for this company (e.g., ADMIN, MANAGER, ACCOUNTANT)', max_length=100, verbose_name='Role Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Company')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='core.company', verbose_name='Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_mappings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Company Mapping',
                'verbose_name_plural': 'User Company Mappings',
                'ordering': ['company__name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_userco_user_id_5bd62d_idx'), models.Index(fields=['company', 'is_active'], name='core_userco_company_e6592d_idx')],
                'unique_together': {('user', 'company')},
            },
        ),
    ]
