# Generated by Django 4.2.30 on 2026-05-07 03:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usercompanymapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict, help_text='Template-specific settings: header_style, footer_text, color_theme, layout_type, show_qr, field_visibility_map')),
                ('logo_override', models.ImageField(blank=True, null=True, upload_to='invoice/logos/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_templates', to='core.company')),
            ],
            options={
                'verbose_name': 'Invoice Template',
                'verbose_name_plural': 'Invoice Templates',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
