# Generated by Django 4.2.30 on 2026-05-20 10:25

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoicetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('SalesInvoice', 'Sales Invoice'), ('PurchaseInvoice', 'Purchase Invoice'), ('CustomerPayment', 'Customer Payment'), ('SupplierPayment', 'Supplier Payment'), ('ReturnOrder', 'Return Order'), ('System', 'System')], max_length=30)),
                ('entity_id', models.CharField(max_length=50)),
                ('risk_score', models.IntegerField(default=0)),
                ('decision_type', models.CharField(choices=[('ALLOW', 'Allow'), ('WARN', 'Warning'), ('SOFT_BLOCK', 'Soft Block'), ('HARD_BLOCK', 'Hard Block'), ('ESCALATE_MANAGER', 'Escalate to Manager')], max_length=20)),
                ('lifecycle_state', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('SUPERSEDED', 'Superseded'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('triggered_rules', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_modules', models.JSONField(default=list)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'lifecycle_state'], name='core_decisi_entity__dace8d_idx'), models.Index(fields=['decision_type', 'lifecycle_state'], name='core_decisi_decisio_b29a86_idx'), models.Index(fields=['timestamp'], name='core_decisi_timesta_d3fee0_idx')],
            },
        ),
    ]
