# Generated by Django 4.2.30 on 2026-05-21 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_decision_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDriftState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=64, unique=True)),
                ('latest_classification', models.CharField(choices=[('A', 'A — Match'), ('B', 'B — Minor Deviation'), ('C', 'C — Financial Drift (CRITICAL)'), ('D', 'D — System Failure')], default='A', max_length=2)),
                ('total_comparisons', models.PositiveIntegerField(default=0)),
                ('class_c_count', models.PositiveIntegerField(default=0, help_text='Number of Class C (Critical) drifts')),
                ('class_d_count', models.PositiveIntegerField(default=0, help_text='Number of Class D (System Failure) drifts')),
                ('is_blocked', models.BooleanField(default=False, help_text='Blocked from Phase 3 migration')),
                ('block_reason', models.TextField(blank=True, help_text='Reason for blocking')),
                ('last_drift_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Module Drift State',
                'verbose_name_plural': 'Module Drift States',
            },
        ),
        migrations.CreateModel(
            name='DriftRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(db_index=True, help_text='Originating module (expenses, returns, payments, purchases, sales)', max_length=64)),
                ('operation', models.CharField(help_text='Operation type (create_entry, reverse_entry, post_entry)', max_length=64)),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Document reference (invoice number, expense number, etc.)', max_length=255)),
                ('classification', models.CharField(choices=[('A', 'A — Match'), ('B', 'B — Minor Deviation'), ('C', 'C — Financial Drift (CRITICAL)'), ('D', 'D — System Failure')], db_index=True, max_length=2)),
                ('financial_impact', models.CharField(choices=[('NONE', 'No financial impact'), ('LOW', 'Low financial impact'), ('HIGH', 'High financial impact'), ('CRITICAL', 'Critical financial impact')], default='NONE', max_length=16)),
                ('engine_entry_id', models.CharField(blank=True, help_text='JournalEntry ID created by JournalEngine', max_length=255)),
                ('gateway_entry_id', models.CharField(blank=True, help_text='JournalEntry ID created by JournalGateway', max_length=255)),
                ('mismatch_detail', models.JSONField(blank=True, default=dict, help_text='Structured mismatch description')),
                ('engine_success', models.BooleanField(null=True)),
                ('gateway_success', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Drift Record',
                'verbose_name_plural': 'Drift Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'classification'], name='core_driftr_module_4e4368_idx'), models.Index(fields=['module', 'created_at'], name='core_driftr_module_e367b0_idx')],
            },
        ),
    ]
