# Generated by Django 4.2.30 on 2026-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_moduledriftstate_driftrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('expenses', 'Expenses'), ('returns', 'Returns'), ('payments', 'Payments'), ('purchases', 'Purchases'), ('sales', 'Sales'), ('accounting', 'Accounting')], db_index=True, max_length=64)),
                ('function', models.CharField(choices=[('create_entry', 'Create Entry'), ('reverse_entry', 'Reverse Entry'), ('post_entry', 'Post Entry')], max_length=64)),
                ('engine_used', models.CharField(choices=[('ENGINE', 'JournalEngine'), ('GATEWAY', 'JournalGateway')], max_length=16)),
                ('execution_hash', models.CharField(blank=True, help_text='SHA-256 of normalized execution parameters', max_length=64)),
                ('financial_signature', models.CharField(blank=True, help_text='SHA-256 of resulting debit/credit lines', max_length=64)),
                ('drift_score', models.IntegerField(default=0, help_text='0=clean, 1-100=drift severity at execution time')),
                ('validation_result', models.CharField(default='PASS', help_text='PASS, FAIL, ROLLED_BACK', max_length=32)),
                ('reference', models.CharField(blank=True, help_text='Document reference', max_length=255)),
                ('duration_ms', models.IntegerField(default=0, help_text='Execution duration in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Migration Log',
                'verbose_name_plural': 'Migration Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=64)),
                ('function', models.CharField(help_text='Operation name (create_entry, reverse_entry, post_entry)', max_length=64)),
                ('state', models.CharField(choices=[('ENGINE', 'Engine — using JournalEngine'), ('READY', 'Ready — passes readiness checks, awaiting switch'), ('GATEWAY', 'Gateway — using JournalGateway'), ('ROLLED_BACK', 'Rolled Back — was Gateway, returned to Engine due to drift')], db_index=True, default='ENGINE', max_length=16)),
                ('switched_at', models.DateTimeField(blank=True, help_text='When this function was switched to Gateway', null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_reason', models.TextField(blank=True)),
                ('gateway_call_count', models.PositiveIntegerField(default=0, help_text='Number of successful Gateway calls')),
                ('drift_count_since_switch', models.PositiveIntegerField(default=0)),
                ('last_execution_hash', models.CharField(blank=True, help_text='SHA-256 of last execution params', max_length=64)),
                ('last_financial_signature', models.CharField(blank=True, help_text='Hash of resulting journal lines', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Migration Config',
                'verbose_name_plural': 'Migration Configs',
                'indexes': [models.Index(fields=['module', 'state'], name='core_migrat_module_b274c3_idx')],
                'unique_together': {('module', 'function')},
            },
        ),
    ]
