# Generated by Django 4.2.30 on 2026-05-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_migrationlog_migrationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_footer',
            field=models.TextField(blank=True, default='', help_text='Footer text on all invoices/receipts'),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='INV', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
